name: neural_graph_composer

channels:
  - pytorch
  - nvidia/label/cuda-11.7.1
  - defaults
  - conda-forge

dependencies:
  - python = 3.10
  - pip
  - pytorch::pytorch >= 1.13
  - pytorch::torchvision
  - pytorch::pytorch-mutex = *=*cuda*
  - pip:
      - torchviz
  - nvidia/label/cuda-11.7.1::cuda-toolkit = 11.7
  - cmake >= 3.11
  - make
  - cxx-compiler
  - gxx = 10
  - nvidia/label/cuda-11.7.1::cuda-nvcc
  - nvidia/label/cuda-11.7.1::cuda-cudart-dev
  - pybind11 >= 2.10.1
  - optree >= 0.4.1
  - typing-extensions >= 4.0.0
  - numpy
  - python-graphviz
  - matplotlib
  - pyyaml
  - tensorboard
  - tqdm
  - aiologger
  - wandb
